title: Web European Conference Official Blog
description: All you need to know about the most important conference about web development in Europe
url: http://blog.webnextconf.eu
subscribe_rss: http://feeds.feedburner.com/imperugo
encoding: utf-8
lang: en-US
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
highlighter: pygments
version: 1.0

# Disqus Comments
disqus_short_name: webeuropeanconference
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-30926898-2
google_analytics_domain: webnextconf.eu

#Socials
twitter_name: webnextconf
facebook_name: WebnextConf
google_plus_name: +UgoLattanzi
github_name: Web-European-Conference

#
# Jekyll Settings
#
markdown: redcarpet
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "page/:num"
category_dir: categories

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
